### ISSUE TITLE
Can't add users as members only or give them this role. 

### ISSUE THREAD

**Issue by patylgoto** [Cyboulette/Group_owners#11]
Congratulations for this feature, it helps us a lot :) 
I would like to share with you 2 problems I've found: 
- when I add a member, he/she is added directly as owner. I can't add a user only as group member 
- after add the user as owner, I can't grant him the role of group member. 
Many thanks.

**Comment by Cyboulette** [comment]
@patylgoto thanks ! Bug has been fixed, and new release is available : https://github.com/Cyboulette/Group_owners/releases/tag/1.0.2 don't hesitate to reopen if not fixed.
