### ISSUE TITLE
Possibility to search for users in the group 

### ISSUE THREAD

**Issue by patylgoto** [Cyboulette/Group_owners#14]
Hello, 

I appreciate this plugin so much, it helps a lot to give autonomie to users :)

In my case, I have groups with 100-1000 people and I was wondering if it's possible to add a search field to find a specific user in the group, please? 

It'd be really useful. 
Many thanks

**Comment by Cyboulette** [comment]
@patylgoto Implemented with #15 you can re-download the code from the repo to update the addon before waiting a new release.

**Comment by patylgoto** [comment]
Fast and effective...It works great! 
Thank you very much
