### ISSUE TITLE
DB not updated (SQLite)

### ISSUE THREAD

**Issue by michael-barchy-cpasbxl** [Cyboulette/Group_owners#6]
Internal Error: SQL Error: SQLSTATE[HY000]: General error: 1 no such table: group_has_owners

**Comment by Cyboulette** [comment]
I will check and keep you updated, I have only tested for MySQL sorry.

**Comment by michael-barchy-cpasbxl** [comment]
Thanks 👍

**Comment by Cyboulette** [comment]
@michael-barchy-cpasbxl it has been fixed, could you please test and reopen issue if necessary ? Thanks !

**Comment by michael-barchy-cpasbxl** [comment]
Thanks. Works great 👍
