### ISSUE TITLE
No icon in menu

### ISSUE THREAD

**Issue by michael-barchy-cpasbxl** [Cyboulette/Group_owners#7]
Would be nice ;-)
![Capture](https://user-images.githubusercontent.com/68649451/108846472-e465d300-75de-11eb-8b9e-779dafaba854.PNG)

**Comment by Cyboulette** [comment]
Nice idea, I will also add an option in the plugin configuration because some themes removes the icon on the menu (like Greenwing theme : https://github.com/Confexion/Greenwing)

**Comment by michael-barchy-cpasbxl** [comment]
Great 👍

**Comment by Cyboulette** [comment]
@michael-barchy-cpasbxl could you please check with latest version and tell me if it's better :) Reopen issue if needed. Thanks.

**Comment by michael-barchy-cpasbxl** [comment]
No luck. Still no icon 😞

**Comment by Cyboulette** [comment]
Did you enable the option on the administration of kanboard ? There is a new setting entry.

**Comment by michael-barchy-cpasbxl** [comment]
Ok got it. Thanks. 👍 
The icon looks bigger 😿 
![image](https://user-images.githubusercontent.com/68649451/109473997-4c4f6a00-7a74-11eb-9af0-0c3396453b32.png)
